# Basic Config
esphome:
  name: "esphome-linky"
  friendly_name: ESPHome - Linky

# https://esphome.io/components/esp8266.html
esp8266:
  board: d1_mini

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

# Enable Web server 
web_server:
  port: 80

# Enable OTA  
ota:

# Wifi Setting
wifi:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} Hotspot

# Hotspot    
captive_portal:

# MQTT Brocker conf
#mqtt:
#  broker: !secret mqtt_broker
#  username: !secret mqtt_user
#  password: !secret mqtt_pass
#  reboot_timeout: 30s    

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: "ESPHome version"
 # UpTime lisible
  - platform: template
    name: "Uptime"
    lambda: |-
      int seconds = (id(uptime_en_seconde).state);
      int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600); 
      int hours = seconds / 3600;
        seconds = seconds % 3600;
      int minutes = seconds /  60;
        seconds = seconds % 60;
      return { (String(days) +" Jours, " + String(hours) +" h, " + String(minutes) +" m, "+ String(seconds) +" s").c_str() };
    icon: mdi:clock-start
    update_interval: 60s
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: "IP"
    ssid:
      name: "SSID"
    bssid:
      name: "BSSID"  

      # Status Binary Sensor: https://esphome.io/components/binary_sensor/status.html
binary_sensor:
  - platform: status
    name: "Status"

# Restart Button: https://esphome.io/components/button/restart.html
button:
  - platform: restart
    name: "Restart"

# https://esphome.io/custom/uart.html
uart:
# TIC
  - id: uart_tic
    rx_pin: GPIO3
    baud_rate: 1200 # 9600 == mode standard, 1200 == mode historique
    parity: EVEN
    data_bits: 7
    stop_bits: 1
# PZEM    
  - id: uart_pzem
    rx_pin: GPIO13
    tx_pin: GPIO15
    baud_rate: 9600

modbus:
  uart_id: uart_pzem

teleinfo:
  uart_id: uart_tic
  update_interval: 5s
  historical_mode: true # false == mode standard, true == mode historique  

# https://esphome.io/components/sensor/index.html
sensor:
  # WiFi
  - platform: wifi_signal
    name: "WiFi Signal"
    unit_of_measurement: dB
    accuracy_decimals: 0
    update_interval: 60s
    icon: mdi:wifi
  # Uptime
  - platform: uptime
    name: "Uptime"
    id: uptime_en_seconde
    unit_of_measurement: s
    accuracy_decimals: 0
    update_interval: 60s
    icon: mdi:clock-start
  # PZEM004T
  - platform: pzemac
    current:
      name: "PZEM Intensité"
    voltage:
      name: "PZEM Tension"
    energy:
      name: "PZEM Énergie"
    power:
      name: "PZEM Puissance"
    frequency:
      name: "PZEM Fréquence"
    power_factor:
      name: "PZEM Facteur de puissance"
    update_interval: 5s   
    
  # TIC MODE STANDARD
  
  # Énergie active soutirée totale
 - platform: teleinfo
   tag_name: "BASE"
   name: "TIC Index Base"
   unit_of_measurement: kWh
   device_class: energy
   state_class: total_increasing
   icon: mdi:flash
   accuracy_decimals: 2
   filters:
     - multiply: 0.001 
  # Courant Efficace
 - platform: teleinfo
   tag_name: "IINST"
   name: "TIC Intensité Instantanée"
   unit_of_measurement: A
   device_class: current
   state_class: measurement
   icon: mdi:current-ac
  # Tension Efficace, phase 1
  - platform: teleinfo
    tag_name: "URMS1"
    name: "TIC Tension"
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    icon: mdi:flash-triangle
  # Puissance app. Instantanée Soutirée
  - platform: teleinfo
    tag_name: "PAPP"
    name: "TIC Puissance Apparente Instantanée Soutirée"
    unit_of_measurement: VA
    state_class: measurement
    device_class: apparent_power
    icon: mdi:gauge
  # Puissance Instantanée Soutirée
  - platform: teleinfo
    tag_name: "CCASN"
    name: "TIC Puissance Soutirée"
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    icon: mdi:gauge

  #----------------------------
  # MODE STANDARD - PRODUCTEURS
  #----------------------------
  
  # Energie active injectée totale
  - platform: teleinfo
    tag_name: "EAIT"
    name: "TIC Energie Injectée"
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:flash
    accuracy_decimals: 2
    filters:
      - multiply: 0.001
  # Puissance app. Instantanée Injectée
  - platform: teleinfo
    tag_name: "SINSTI"
    name: "TIC VA Instantanée Injectée"
    unit_of_measurement: VA
    state_class: measurement
    device_class: apparent_power
    icon: mdi:gauge
  # Puissance app. Maximale Injectée
  - platform: teleinfo
    tag_name: "SMAXIN"
    name: "TIC VA Max Injectée"
    unit_of_measurement: VA
    state_class: measurement
    device_class: apparent_power
    icon: mdi:gauge
  # Puissance Instantanée injectée
  - platform: teleinfo
    tag_name: "CCAIN"
    name: "TIC Puissance Injectée"
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    icon: mdi:gauge
